# Generated by Django 4.0.4 on 2022-04-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polloption',
            old_name='pool',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='pool_option',
            new_name='poll_option',
        ),
    ]
