# Generated by Django 4.0.4 on 2022-05-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_pool_polloption_poll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='date_start',
        ),
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
